#!/bin/bash
# Writes Generated/BuildStamp.swift with a fresh, per-build identity: a short git hash plus a
# build timestamp (a UUID fallback when not in a git checkout). This changes on every build, so
# the app, host, and relay can each tell exactly which build they are and detect when they're
# talking to a stale peer from a different install. Run before `xcodegen generate` (so the file
# is in the source list) and again as a pre-build step (so each rebuild is fresh).
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="Sources/MacControlMCPCore/BuildStamp.swift"
:

GIT_HASH="$(git rev-parse --short=12 HEAD 2>/dev/null || true)"
GIT_DIRTY=""
if [ -n "$GIT_HASH" ] && ! git diff --quiet 2>/dev/null; then GIT_DIRTY="-dirty"; fi
STAMP_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [ -n "$GIT_HASH" ]; then
  BUILD_ID="${GIT_HASH}${GIT_DIRTY}+${STAMP_DATE}"
else
  BUILD_ID="$(uuidgen)+${STAMP_DATE}"
fi

# Only rewrite when the id line actually changed, to avoid needless recompiles when a pre-build
# run lands within the same second as an earlier one (the date has second resolution).
NEW_LINE="    public static let buildId = \"${BUILD_ID}\""
if [ -f "$OUT" ] && grep -qF "$NEW_LINE" "$OUT"; then
  exit 0
fi

cat > "$OUT" <<EOF
// Generated by scripts/gen-build-stamp.sh — do not edit; not checked in (see .gitignore).
// A unique identity per build, so components can detect a stale peer from a different install.
public enum BuildStamp {
${NEW_LINE}
    public static let builtAt = "${STAMP_DATE}"
}
EOF
