#!/bin/bash
# Writes Sources/MacControlMCPCore/BuildStamp.swift with the exact-binary identity for THIS build:
# the short git hash (and -dirty) plus a build timestamp. This is supplementary to the committed,
# monotonically-incrementing marketing/build version (see scripts/bump-version.sh) — it pins which
# commit and moment a binary came from, for debugging. Run before `xcodegen generate` (so the file
# is in the source list). The file is gitignored.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="Sources/MacControlMCPCore/BuildStamp.swift"

GIT_HASH="$(git rev-parse --short=12 HEAD 2>/dev/null || true)"
GIT_DIRTY=""
if [ -n "$GIT_HASH" ] && ! git diff --quiet 2>/dev/null; then GIT_DIRTY="-dirty"; fi
STAMP_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
if [ -n "$GIT_HASH" ]; then
  BUILD_ID="${GIT_HASH}${GIT_DIRTY}+${STAMP_DATE}"
else
  BUILD_ID="$(uuidgen)+${STAMP_DATE}"
fi

cat > "$OUT" <<EOF
// Generated by scripts/gen-build-stamp.sh — do not edit; not checked in (see .gitignore).
// Exact-binary identity (git hash + build time), supplementary to the committed marketing/build
// version. Lets components pin which commit and moment a binary came from.
public enum BuildStamp {
    public static let buildId = "${BUILD_ID}"
    public static let builtAt = "${STAMP_DATE}"
}
EOF
