#!/bin/bash
#
# gen-identity.sh — writes the identity this build compiles against.
#
# MacControlMCP ships through channels that install to different places: install.sh and the
# Homebrew cask own /Applications, while the PyPI wheel installs to ~/Applications because an
# unattended `uvx` bootstrap cannot obtain the privileges the system folder needs.
#
# Two copies of ONE identity cannot coexist. They register the same LaunchAgent Label, listen on
# the same Mach service, and each terminates any host running from a bundle other than its own — so
# whichever launched last silently owns the stack, and the version a caller sees is whichever that
# was. The XPC requirement pins team and identifier but not path, so nothing detects the swap.
#
# So the user-installed build is a genuinely different product: its own bundle identifiers, its own
# Label, its own Mach service. The two then ignore each other entirely.
#
# Everything derives from one base identifier. Generating it — rather than hardcoding the variants —
# is what keeps the Swift constants, the LaunchAgent plist, and the bundle identifiers in project.yml
# from drifting apart.
#
# Usage:
#   ./scripts/gen-identity.sh [--variant system|user]
#
# Options:
#   --variant NAME   system (default) installs to /Applications; user installs to ~/Applications
#                    and carries the `.user` identifier suffix.
#   -h, --help       Show this message and exit.
#
# Writes (both generated, both gitignored):
#   Sources/MacControlMCPCore/AppIdentity.swift   compiled-in constants
#   Generated/host.launchagent.plist              the LaunchAgent the app bundle embeds
#
# Prints the identifier suffix on stdout, so a caller can pass it to xcodebuild as
# IDENTITY_SUFFIX and keep the bundle identifiers in step with the compiled-in ones.
#
set -euo pipefail
cd "$(dirname "$0")/.."

TEAM_ID="P8MA38JTXY"
BASE="com.nuclearcyborg.maccontrol"
VARIANT="system"

while [ $# -gt 0 ]; do
  case "$1" in
    --variant) VARIANT="${2:?--variant needs a value}"; shift 2 ;;
    -h|--help) sed -n '2,/^set -euo/{/^set -euo/!p;}' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "gen-identity: unknown option: $1" >&2; exit 2 ;;
  esac
done

# The tilde in INSTALL_DIRECTORY is deliberate and must NOT expand: the value is display text
# embedded into Swift guidance ("installed to ~/Applications"), never used as a path here.
# shellcheck disable=SC2088
case "$VARIANT" in
  system) SUFFIX=""; INSTALL_DIRECTORY="/Applications" ;;
  user)   SUFFIX=".user"; INSTALL_DIRECTORY="~/Applications" ;;
  *) echo "gen-identity: --variant must be 'system' or 'user' (got '$VARIANT')" >&2; exit 2 ;;
esac

# The suffix appends to each COMPLETE identifier rather than to the base, so the host reads
# ...maccontrol.host.user and not ...maccontrol.user.host — the role stays where a reader expects
# it, and PRODUCT_BUNDLE_IDENTIFIER in project.yml is a plain "<identifier>$(IDENTITY_SUFFIX)".
APP_ID="${BASE}${SUFFIX}"
HOST_ID="${BASE}.host${SUFFIX}"
RELAY_ID="${BASE}.relay${SUFFIX}"
MACH_SERVICE="${TEAM_ID}.${HOST_ID}"

# The plist's FILE NAME stays constant across variants while its Label does not. SMAppService
# resolves the name inside the calling app's own bundle, so two bundles each holding their own
# file at the same relative path are unambiguous — and keeping it fixed means the copy step in
# project.yml needs no variant-specific paths.
PLIST_NAME="${BASE}.host.plist"

mkdir -p Generated

cat > Sources/MacControlMCPCore/AppIdentity.swift <<SWIFT
// Generated by scripts/gen-identity.sh — do not edit; not checked in (see .gitignore).
//
// The identity this build compiles against. Every identifier derives from \`base\`, so the
// system build (/Applications) and the user build (~/Applications) are different products
// rather than two copies contending for one LaunchAgent Label and one Mach service.

public enum AppIdentity {
    /// Which install location this build belongs to: "system" or "user".
    public static let variant = "${VARIANT}"

    /// Developer ID team. The host's Mach service is team-scoped, so this is part of its name.
    public static let teamID = "${TEAM_ID}"

    /// The root every other identifier is built from.
    public static let base = "${APP_ID}"

    public static let appBundleID = "${APP_ID}"
    public static let hostBundleID = "${HOST_ID}"
    public static let relayBundleID = "${RELAY_ID}"

    /// The LaunchAgent's job label — distinct per variant, which is what stops the two builds
    /// from taking the host from each other.
    public static let launchAgentLabel = "${HOST_ID}"

    /// The plist's file name inside \`Contents/Library/LaunchAgents\`. Constant across variants;
    /// SMAppService resolves it within the calling app's own bundle, so it needs no suffix.
    public static let launchAgentPlistName = "${PLIST_NAME}"

    /// The team-scoped Mach service the host listens on and the relay connects to.
    public static let machServiceName = "${MACH_SERVICE}"

    /// Where this build expects to have been installed. Informational — used in guidance text.
    public static let expectedInstallDirectory = "${INSTALL_DIRECTORY}"

    /// What the host accepts from a connecting caller: our team AND specifically this variant's
    /// signed relay or GUI, not just any same-team binary. Pinning the identifier closes the
    /// confused-deputy hole, and pinning it *per variant* keeps the two builds' stacks apart.
    public static let callerRequirement =
        #"anchor apple generic and certificate leaf[subject.OU] = "${TEAM_ID}" and (identifier "${RELAY_ID}" or identifier "${APP_ID}")"#

    /// What the relay requires of the host it connects to (mutual auth).
    public static let hostRequirement =
        #"anchor apple generic and certificate leaf[subject.OU] = "${TEAM_ID}" and identifier "${HOST_ID}""#
}
SWIFT

cat > Generated/host.launchagent.plist <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/gen-identity.sh — do not edit; not checked in (see .gitignore). -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${HOST_ID}</string>
  <key>BundleProgram</key><string>Contents/Helpers/MacControlHost.app/Contents/MacOS/MacControlHost</string>
  <key>MachServices</key>
  <dict>
    <key>${MACH_SERVICE}</key><true/>
  </dict>
  <key>AssociatedBundleIdentifiers</key>
  <array><string>${APP_ID}</string></array>
</dict>
</plist>
PLIST

plutil -lint Generated/host.launchagent.plist >/dev/null \
  || { echo "gen-identity: generated plist is not valid" >&2; exit 1; }

echo "$SUFFIX"
